"""30 days of faceless image posts that point to the shop.
Each post: hook (big text on the card), points (card body), caption, product it sells."""

SHOP = "struggle92-shop.vercel.app"

POSTS = [
    ("Stop paying for subscriptions you forgot about",
     ["Search your bank app for 'monthly'", "List every charge on one page", "Cancel anything unused for 30 days", "Set one reminder before each free trial ends"],
     "Most people find at least one charge they forgot. Do this check once a month.", "planner"),
    ("3 money rules I wish I knew at 20",
     ["Pay yourself first, even $10", "Never finance something that loses value", "Track it or it disappears"],
     "Rule 3 is the one nobody does. A 10-minute weekly check fixes it.", "planner"),
    ("You don't need to show your face to post Shorts",
     ["Screen-record tutorials", "Text-story videos", "Voiceover explainers", "Hands-only demos", "List videos with stock clips"],
     "5 faceless formats you can start today with a phone and free apps.", "playbook"),
    ("The first 2 seconds decide everything",
     ["Put the payoff in line one", "Cut every 'hey guys'", "Show the result before the how", "Text on screen in the first frame"],
     "If the hook fails nothing else matters. 60 fill-in-the-blank hooks are in the playbook.", "playbook"),
    ("Zero-based budget in 4 steps",
     ["Write this month's income", "Give every dollar a job", "Bills, savings, debt, fun", "Income minus jobs = $0"],
     "Zero doesn't mean broke. It means every dollar has a plan.", "planner"),
    ("Batch a week of videos in one afternoon",
     ["Write 7 hooks first", "Film all clips in one go", "Edit in one CapCut session", "Schedule, then stop thinking about it"],
     "Consistency beats talent. Batching makes it easy.", "playbook"),
    ("Snowball vs avalanche: which debt first?",
     ["Snowball: smallest balance first for quick wins", "Avalanche: highest interest first, saves the most", "Pick the one you'll actually stick to"],
     "The best plan is the one you finish.", "planner"),
    ("Your side hustle profit is lower than you think",
     ["Subtract platform fees", "Subtract shipping and supplies", "Subtract ads", "Set aside money for taxes"],
     "Revenue isn't profit. Log every sale with its real costs.", "planner"),
    ("Free apps for faceless content",
     ["CapCut: edit + auto captions", "Canva: covers and text slides", "Phone screen recorder", "Free stock clips sites"],
     "You don't need to buy gear to start.", "playbook"),
    ("Sinking funds stop 'surprise' expenses",
     ["Car repairs", "Birthdays and holidays", "Annual subscriptions", "Phone replacement"],
     "Divide the yearly cost by 12 and save it monthly. No more surprises.", "planner"),
    ("3 things nobody tells you about posting daily",
     ["Most videos flop, that's normal", "Your 30th video beats your 1st", "Repost winners with a new hook"],
     "Track views after 48 hours and repeat what works.", "playbook"),
    ("The $5,000 savings challenge",
     ["100 boxes, different amounts", "Color one in each time you save", "Any order, any pace", "Watch it fill up"],
     "Seeing progress makes saving stick. The chart is in the planner.", "planner"),
    ("Captions safe zone for Shorts and TikTok",
     ["Keep text out of the bottom 20%", "Stay off the right edge buttons", "Big, high-contrast font", "Max 6 words per line"],
     "Hidden captions kill retention.", "playbook"),
    ("10-minute weekly money check",
     ["Log this week's spending", "Check upcoming bills", "Move money to savings", "One thing to cut next week"],
     "10 minutes a week beats a 3-hour panic once a year.", "planner"),
    ("Out of video ideas? Use this",
     ["Mistakes beginners make", "Tools you use every week", "A common myth, busted", "Before and after", "Explain one term in 30s"],
     "A full 30-day calendar of ideas is inside the playbook.", "playbook"),
    ("Bills you should check once a year",
     ["Car insurance", "Phone plan", "Internet", "Streaming bundles"],
     "One call or comparison can lower some of these. Track them all on one page.", "planner"),
    ("Hook formulas that work in any niche",
     ["Stop doing [X] if you want [Y]", "Nobody tells you this about [X]", "[X] explained in 30 seconds", "I tried [X] for 7 days"],
     "Fill in the blanks for your niche.", "playbook"),
    ("Starting a side hustle with a full-time job",
     ["Pick one thing, not five", "Block 3 fixed hours a week", "Track every dollar in and out", "Review monthly, cut what's not working"],
     "Small and consistent beats big and burnt out.", "bundle"),
    ("Net worth in one line",
     ["What you own", "minus what you owe", "= your net worth", "Check it every 3 months"],
     "The number matters less than the direction it's moving.", "planner"),
    ("Weekly review for creators",
     ["Which video got the most views?", "What was its hook?", "Make 2 more like it", "Drop what flopped twice"],
     "Data beats guessing. 5 minutes a week.", "playbook"),
    ("Spending leaks that add up",
     ["Delivery fees", "Daily coffee runs", "Unused gym membership", "In-app purchases"],
     "Not saying never. Saying know the number.", "planner"),
    ("How to write a script in 5 minutes",
     ["Hook: the payoff", "3 quick points", "One clear takeaway", "Tell them what to do next"],
     "Short scripts, fast edits, more posts.", "playbook"),
    ("Pay off debt faster without earning more",
     ["List every debt with its interest rate", "Pay minimums on all but one", "Throw every extra dollar at that one", "Roll it over when it's gone"],
     "The debt payoff tracker makes it visual.", "planner"),
    ("Content and money: the 2 systems you need",
     ["A content system to get attention", "A money system to keep what you earn", "Both take 10 minutes a day", "Start with one, add the other"],
     "Both are in the Starter Bundle.", "bundle"),
    ("Export settings for Shorts",
     ["9:16 vertical, 1080x1920", "30 fps", "Under 60 seconds", "Captions burned in"],
     "Bad export = blurry video = swipe.", "playbook"),
    ("Budget for irregular income",
     ["Budget off your lowest month", "Extra goes to a buffer first", "Then debt, then savings", "Pay yourself a fixed 'salary'"],
     "Works for gig work, tips and side hustles.", "planner"),
    ("Why faceless channels work",
     ["Less pressure, more posting", "Easy to batch", "Topic matters more than face", "Works for shy people"],
     "The system matters more than the camera.", "playbook"),
    ("A money goal you'll actually hit",
     ["Make it a number", "Give it a date", "Break it into weekly amounts", "Track it where you see it"],
     "'Save more' isn't a goal. '$600 by March' is.", "planner"),
    ("30 posts in 30 days, no face",
     ["One format a day", "Same time every day", "Review every Sunday", "Keep what works"],
     "The calendar, hooks and workflow are in the playbook.", "playbook"),
    ("Your first month plan",
     ["Week 1: track every dollar", "Week 2: cut one leak", "Week 3: post 5 videos", "Week 4: review and repeat"],
     "Get both systems in the Side Hustle Starter Bundle.", "bundle"),
]

PRICES = {"planner": "$4.99", "playbook": "$27", "bundle": "$29"}
NAMES = {"planner": "Hustle Money Planner", "playbook": "Faceless Shorts Playbook", "bundle": "Side Hustle Starter Bundle"}
TAGS = {
    "planner": "#budgeting #moneytips #personalfinance #budgetplanner #savemoney",
    "playbook": "#facelesscontent #youtubeshorts #contentcreator #tiktoktips #sidehustle",
    "bundle": "#sidehustle #moneytips #contentcreator #budgeting #facelesscontent",
}


def caption(post):
    hook, _, line, product = post
    return (f"{hook}\n\n{line}\n\n"
            f"{NAMES[product]} ({PRICES[product]}, instant download): {SHOP}\n\n"
            f"{TAGS[product]}")
